spring.application.name=Week7Learning

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/week7db?useSSL=false&allowPublicKeyRetrieval=true
#=jdbc:postgresql://localhost:5432/week7db?useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=postgres
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true